export enum GameCharacters{
    PRINCE = "prince",
    BLACK_PUDDING = "black_pudding",
    BLUE_PUDDING = "blue_pudding",
    AQUA_PUDDING = "aqua_pudding",
    BIOLUMINESCENT_PUDDING = "bioluminescent_pudding",
    EGGYOLK_PUDDING = "eggyolk_pudding",
    EVILCYAN_PUDDING = "evilcyan_pudding",
    GREEN_PUDDING = "green_pudding",
    ICEBLUE_PUDDING = "iceblue_pudding",
    MOON_PUDDING = "moon_pudding",
    PINK_PUDDING = "pink_pudding",
    PURPLE_PUDDING = "purple_pudding",
    RED_PUDDING = "red_pudding",
    VOID_PUDDING = "void_pudding",
    WEIRDGREEN_PUDDING = "weirdgreen_pudding",
    YELLOW_PUDDING = "yellow_pudding",
    TROLL = "troll",
    EXIT = "exit",
    
}